bloq_editor:
    editorial_contents:
        article:
            model_class: &articleModelClass Bloq\Common\EditorBundle\Entity\Article
            manager_class: Bloq\Common\EditorBundle\Manager\ArticleManager
            form_type_class: Bloq\Common\EditorBundle\Form\Type\ArticleFormType
            form_type_name: editor_article_edition
#        gallery:
#            model_class: ~
#            manager_class: ~
#            form_type_class: ~
#            form_type_name: ~

bloq_multimedia:
    images:
        root_dir_path: %editor.domain.path%%multimedia.images.save.path%
        root_dir_url: %multimedia.images.dir.rel_url%

parameters:
    article.model_class: *articleModelClass
