bloq_editor:
    editorial_contents:
        article:
            model_class: Bloq\Common\EditorBundle\Entity\Article
            manager_class: Bloq\Common\EditorBundle\Manager\ArticleManager
            form_type_class: Bloq\Common\EditorBundle\Form\Type\ArticleFormType
            form_type_name: editor_article_edition
        gallery:
            model_class: ~
            manager_class: ~
            form_type_class: ~
            form_type_name: ~