fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#fos_user_registration_register:
#    path:      /users/create/
#    defaults:  { _controller: FOSUserBundle:Registration:register }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

Migration:
    resource: "@AppBundle/Controller/MigratorController.php"
    type:     annotation

Preview:
    resource: "@AppBundle/Controller/PreviewController.php"
    type:     annotation

Admin:
    resource: "@AppBundle/Controller/AdminController.php"
    type:     annotation

Editor:
    resource: "@AppBundle/Controller/EditorController.php"
    type:     annotation

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

