parameters:
    app.entity.user.class: 'Bloq\Common\EntitiesBundle\Entity\User'
    app.entity.site.class: 'Bloq\Common\EntitiesBundle\Entity\Site'
    app.manager.site.class: 'Bloq\Common\EntitiesBundle\Manager\SiteManager'
    app.manager.editorial_content.class: 'AppBundle\Manager\EditorialContentManager'

services:
    app.manager.site:
        class: %app.manager.site.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - %app.entity.site.class%

    app.manager.editorial_content:
        class: %app.manager.editorial_content.class%
        arguments:
            - "@doctrine.orm.entity_manager"
