# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.entity.user.class: 'AppBundle\Entity\User'
    app.entity.site.class: 'AppBundle\Entity\Site'
    app.manager.site.class: 'AppBundle\Manager\SiteManager'
    app.user.creation.form.type: app_user_creation
    app.user.creation.form.handler: app.user_creation.form.handler.default
    app.user.creation.form.name: app_user_creation_form
#    parameter_name: value

services:
#    app.user_creation.form:
#        class: Symfony\Component\Form\Form
#        factory: ["@form.factory", createNamed]
#        arguments:
#            - %app.user.creation.form.name%
#            - %app.user.creation.form.type%
#            - null
#            - {validation_groups: %fos_user.registration.form.validation_groups%}

    app.user_creation.form.type:
        class: AppBundle\Form\Type\UserCreationFormType
        tags:
            - { name: form.type, alias: app_user_creation }
        arguments:
            - %app.entity.user.class%
            - %security.role_hierarchy.roles%
            - "@=service('security.authorization_checker')"

    app.user_creation.form.handler:
        class: AppBundle\Form\Handler\UserCreationFormHandler
        arguments:
            - "@fos_user.registration.form"
            - "@request"
            - "@fos_user.user_manager"
            - "@fos_user.mailer"
            - "@fos_user.util.token_generator"
            - "@session"
        scope: request
        public: false

    app.manager.site:
        class: %app.manager.site.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - %app.entity.site.class%
